# ---------- BUILD ----------
FROM golang:1.25-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o app cmd/server/main.go

# ---------- RUN ----------
FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/app /app/app

ENV PORT=8080
EXPOSE 8080

CMD ["/app/app"]